version: 2.1
commands:
  install_deps:
    step:
      - run:
          name: Install Dependencies
          commands: |
            npm install
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_deps

workflows:
  version: 2
  build-test-package:
    jobs:
      - build