version: 2.1

commands:

  install_deps: 
    steps:
      - restore_cache: 
          key: node-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: |
            cd src/
            npm install
      - save_cache:
          key: node-cache-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules
  
  unit_test:
    steps:
      - run:
          name: Unit Testing
          environment:
            MOCHA_FILE: mocha-unit-test/test-results.xml
          command: |
            cd src
            mkdir -p mocha-unit-test
            npm run test-unit
      - store_test_results: 
          path: src/mocha-unit-test

  cc_report:
    steps:
      - run:
          name: Collect Code Coverage Reports
          command: |
            cd src/
            npm run test-coverage

          
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_deps
      - unit_test
  
  code-coverage-report:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_deps
      - cc_report

workflows:
  version: 2
  build-test-package:
    jobs:
      - ci-build
      - code-coverage-report:
          requires:
            - ci-build