version: 2.1

commands:

  install_deps: 
    steps:
      - restore_cache: 
          key: node-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: |
            cd src/
            npm install
      - save_cache:
          key: node-cache-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules
            
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_deps

workflows:
  version: 2
  build-test-package:
    jobs:
      - build