version: 2.1

commands:

  install_deps: 
    steps:
      - restore_cache: 
          key: node-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: |
            cd src/
            npm install
      - save_cache:
          key: node-cache-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules
  
  unit_test:
    steps:
      - run:
          name: Unit Testing
          environment:
            MOCHA_FILE: mocha-unit-test/test-results.xml
          command: |
            cd src
            mkdir -p mocha-unit-test
            npm run test-unit
      - store_test_results: # This step here will upload the test results to circleci
          path: src/mocha-test

            
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_deps
      - unit_test

workflows:
  version: 2
  build-test-package:
    jobs:
      - build