version: 2.1
commands:
  install_deps: # Name of command for installing dependencies along with cache restore/save function
    steps:
      - restore_cache: # This step will try and attempt to restore dependency cache
          ke y: node-cache-{{ checksum "src/package.json" }} # I use checksum of json because if theres change in package.json then it will automatically reinstall the package.
      - run:
          name: Install dependencies
          command: | # These command here will install dependency modules from package.json
            cd src/
            npm install
      - save_cache: # This step here will save the installed dependencies to a cache
          key: node-cache-{{ checksum "src/package.json" }} # Using this key in restore_cache will retrieve this cache
          paths:
            - src/node_modules
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - install_deps

workflows:
  version: 2
  build-test-package:
    jobs:
      - build